plugins {
    id "org.gradle.toolchains.foojay-resolver-convention" version "1.0.0"
    id "nl.elec332.gradle.minecraft.moddev" version "1.2.1"
}

moddev {
    enableForge()
    enableNeoForge()
    enableFabric()
//    enableQuilt() //No point yet as Quilt loads fabric mods

    superCommonMode = true
    useBuildNumber = true
    allJarOnly = true

    javaToolchainVersion = 17
}
